name: janus-ci

on:
  push:
    branches: [main, master, dev]
    tags: ['*']
  pull_request:
    branches: [main, master, dev]

permissions:
  contents: read
  packages: write # Required for pushing Docker images to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        datachannels: ["yes", "no"]
        libcurl: ["yes", "no"]
        include:
          - datachannels: "yes"
            libcurl: "yes"
            deps_from_src: "yes"
            janus_config_opts: ""
          - datachannels: "yes"
            libcurl: "no"
            deps_from_src: "no"
            janus_config_opts: "--disable-aes-gcm -disable-mqtt --disable-mqtt-event-handler --disable-turn-rest-api --disable-sample-event-handler"
          - datachannels: "no"
            libcurl: "yes"
            deps_from_src: "no"
            janus_config_opts: "--disable-aes-gcm -disable-mqtt --disable-mqtt-event-handler --disable-data-channels"
        exclude:
          - datachannels: "no"
            libcurl: "no"
    env:
        CC: ${{ matrix.compiler }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: prep
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}/janus
            vedeht/janus
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: ${{ steps.prep.outputs.labels }}

  javascript-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: |
          cd npm
          npm install
      - name: Run ESLint
        run: |
          cd npm
          npm run lint

  javascript-dist:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: |
          cd npm
          npm install
      - name: Make dist files
        run: |
          cd npm
          npm run prerelease
      - uses: actions/upload-artifact@v4
        with:
          name: janus.es.js
          path: npm/dist/janus.es.js
